spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/trynewmenu
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update