spring:
  datasource:
    url: jdbc:mysql://ls-45e2f43e0ca15952de0950cc600c5d42d3eb229f.czujmy3n63ug.ap-northeast-2.rds.amazonaws.com/trynewmenu
    username: dbmasteruser
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update