spring:
  datasource:
    url: jdbc:mysql://database-trynewmenu.cqahz3tmmzgt.ap-northeast-2.rds.amazonaws.com/trynewmenu?useUnicode=true&characterEncoding=utf8
    username: admin
    password: N6OOoRwNpnpW4k63pyNe
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update